.github/workflows/main.yml, Cargo.toml, src/lib.rs, src/unix.rs, src/wasm.rs, src/windows.rs, tests/client-dropped-before-command-tokio.rs, tests/client-dropped-before-command.rs, tests/client-of-myself.rs, tests/make-as-a-client.rs, tests/server.rs
=> Fix potentially dropped Client in configure

Cargo.toml, src/lib.rs, tests/client-dropped-before-command-tokio.rs, tests/client-dropped-before-command.rs, tests/client-of-myself.rs, tests/client.rs, tests/helper.rs, tests/make-as-a-client.rs, tests/server.rs
=> Rename crate to `jobslot`

Cargo.toml
=> Add back Alex Crichton as an author

Cargo.toml, src/lib.rs, src/unix.rs, src/wasm.rs, src/windows.rs
=> Refactor src, minor optimization and add doc

Cargo.toml, src/lib.rs, src/unix.rs, src/wasm.rs, src/windows.rs
=> Further refactor

Cargo.toml
=> Bump crate ver to v0.2.0

Cargo.toml
=> Bump crate ver to v0.2.1

Cargo.toml
=> Bump crate ver to v0.2.2

.github/workflows/msrv.yml, Cargo.toml
=> Add msrv CI

src/unix.rs
Replace signal handling with `poll`ing.
=> Improve unix impl

src/lib.rs, src/unix.rs, src/utils.rs, src/wasm.rs, src/windows.rs
=> Fix unix impl

README.md
=> Update section of README on why fork `jobserver`

Cargo.toml, README.md, src/windows.rs
=> Improve win impl

src/lib.rs, src/unix.rs
=> Refactor & Optimize

src/lib.rs, src/unix.rs, src/windows.rs
=> More Refactor and Optimization

src/windows.rs
=> Optimize `windows::Client::new`: Avoid repeated `String` creation

src/unix.rs
=> Update comment in `unix::Client::acquire`

.github/workflows/msrv.yml, Cargo.toml
=> Bump msrv to 1.54

.github/workflows/msrv.yml, Cargo.toml
=> Bump msrv to 1.56 as required by windows-sys 0.48

.github/workflows/cache-cleanup.yml
in additional to caches for PRs.
=> Cleanup gh caches for branches

Cargo.toml, src/unix.rs
With removal of outdated comment
=> Release jobslot v0.2.14

.github/workflows/publish.yml
=> Add CI workflow `publish.yml` for automatic publish

.github/workflows/main.yml
wasm32-wasi has been renamed to wasm32-wasip1
=> CI: Fix wasm testing
